### ISSUE TITLE
Can't build from source without transifex account

### ISSUE THREAD

**Issue by zedalaye** [cozy-labs/cozy-desktop#1056]
### Description

It looks like Cozy Desktop can not be built without a transifex account.

### Steps to Reproduce

1. Clone source code
2. install dependencies
3. yarn install
4. yarn build

### Expected behavior

Cozy Desktop is built

### Actual behavior

```
...
$ tx pull --all --minimum-perc=1 || true
tx INFO: No credentials file was found at /home/pierre/.transifexrc.
tx INFO: Created /home/pierre/.transifexrc 
[?] Enter your api token: 
```
### Informations

* **reproductible**: always
* **OS**: Linux, Ubuntu 18.04
* **version**: master

**Comment by sebn** [comment]
Closing this one, assuming the hint helped. Feel free to reopen in case you're still stuck and we'll get back to you :smiley:
