### ISSUE TITLE
Auto upgrade doesn't change .desktop autostart file

### ISSUE THREAD

**Issue by VilainMamuth** [cozy-labs/cozy-desktop#1107]
### Description

After an auto upgrade, CozyDrive autostart is broken

### Steps to Reproduce

1. Install CozyDrive-3.8.1-x86_64.AppImage
2. CozyDrive updates to CozyDrive-3.9.0-x86_64.AppImage
3. Autostart file is .config/autostart/CozyDrive-3.8.1-x86_64.AppImage.desktop and contains
[Desktop Entry]
Type=Application
Version=1.0
Name=CozyDrive-3.8.1-x86_64.AppImage
Comment=CozyDrive-3.8.1-x86_64.AppImagestartup script
Exec=/home/manu/Applications/CozyDrive-3.8.1-x86_64.AppImage --hidden
StartupNotify=false
Terminal=false

### Expected behavior

The desktop file should be named without version info
At least, the Exec line should be updated after the upgrade.

**Comment by sebn** [comment]
Hello there, thank you for reporting the issue!

Could you possibly have moved the `CozyDrive-3.8.1-x86_64.AppImage` after the first run?
This is [known to prevent the desktop file to be modified during auto-update](https://github.com/cozy-labs/cozy-desktop/blob/master/KNOWN_ISSUES.md#gnulinux-integration).

**Comment by sebn** [comment]
My bad, this is actually not the same issue.
You're right, the exec line may not have been updated. Thanks.

**Comment by sebn** [comment]
Sorry for the delay. This is the next one on our task list once 3.9.1-beta.1 is released.

**Comment by taratatach** [comment]
@VilainMamuth I don't know if you've noticed but we've now changed the way we handle the autostart file and you shouldn't have to re-enable autostart after an upgrade anymore.

Feel free to tell us if you're still experiencing the issue with the most recent version and I'll re-open if necessary.
