### ISSUE TITLE
Configuration fails with logged message "electronFetch is not a function"

### ISSUE THREAD

**Issue by guillp** [cozy-labs/cozy-desktop#1125]
### Description

When running cozy-desktop for the first time, it needs to be configured for your user account by entering your account specific cozy url. This fails for me, with no error message on the GUI, but an error in the logs:

{"name":"Cozy Desktop","hostname":"guillaume-pc","pid":1876,"component":"GUI","level":50,"err":{"message":"electronFetch is not a function","name":"TypeError","stack":"TypeError: electronFetch is not a function\n    at global.fetch (/usr/lib/cozy-desktop/resources/app.asar/gui/js/proxy.js:78:12)\n    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/cozy-client-js/dist/webpack:/src/index.js:284:26\n    at doTry (/usr/lib/cozy-desktop/resources/app.asar/node_modules/cozy-client-js/dist/webpack:/src/utils.js:42:12)\n    at Client.isV2 (/usr/lib/cozy-desktop/resources/app.asar/node_modules/cozy-client-js/dist/webpack:/src/index.js:284:14)\n    at Client.authorize (/usr/lib/cozy-desktop/resources/app.asar/node_modules/cozy-client-js/dist/webpack:/src/index.js:231:28)\n    at Registration.process (/usr/lib/cozy-desktop/resources/app.asar/core/remote/registration.js:83:17)\n    at App.registerRemote (/usr/lib/cozy-desktop/resources/app.asar/core/app.js:120:25)\n    at OnboardingWM.onRegisterRemote (/usr/lib/cozy-desktop/resources/app.asar/gui/js/onboarding.window.js:104:13)\n    at emitTwo (events.js:126:13)\n    at EventEmitter.emit (events.js:214:7)\n    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:286:13)\n    at emitTwo (events.js:126:13)\n    at WebContents.emit (events.js:214:7)"},"msg":"electronFetch is not a function","time":"2018-08-11T08:11:57.317Z","v":0}

### Steps to Reproduce

1. Run cozy-desktop
2. Click "Sign-in to my cozy"
3. Enter your account specific URL
4. Click Next

### Expected behavior
Something should happen (like asking for my password)

### Actual behavior
The loader in the "Next" button keeps turning forever.
The line above gets added to the logs in ~/.cozy-desktop/logs.txt

### Informations

* **reproductible**: always
* **OS**: Linux 64bits (Up-to-date Manjaro) 
* **version**: 3.9.0

**Comment by sebn** [comment]
Hello there, thank you for reporting this!
This is definitely a bug. We'll investigate soon.

**Comment by ArchangeGabriel** [comment]
@guillp Were you using the distro package? If so this has been long fixed (https://forum.cozy.io/t/resolu-arch-linux-electronfetch-is-not-a-function/6051/4).

**Comment by guillp** [comment]
I confirm that it is fixed, thanks !
