### ISSUE TITLE
Enhance README.md

### ISSUE THREAD

**Issue by enguerran** [cozy-labs/cozy-desktop#1141]
I start working on Cozy Drive for Desktop and I use [my super power of the new comer](https://vimeo.com/70067975) to see what cannot be seen anymore by old developers with their noses in it (no offense :nose:).

I suggest to revamp the documentation organization starting by the welcome documentation: https://github.com/enguerran/cozy-desktop/blob/feat/doc/README.md

Here is a TL;DR with the general plan, inspired by [`vscode`](https://github.com/microsoft/vscode):

---

# Title
{badges}

Introduction about the application.

## Contributing

Links to the different documentations to contribute.

## Feedback

Let users know how to reach us.

## Licence

---

What do you think?

**Comment by sebn** [comment]
I would have kept a link to the download page and/or the user documentation (not a broken link as it seems to be the case currently).

Aside from that, the new plan looks good to me!

**Comment by enguerran** [comment]
I agree with you, do you think this downliad link is discoverable enough?
- link to download page: https://github.com/enguerran/cozy-desktop/commit/09d16ce53d4698eabf815a588e57d057edaf3f0e#diff-04c6e90faac2675aa89e2176d2eec7d8R16

Do you know where I can find the official documentation that was linked here: https://github.com/enguerran/cozy-desktop/commit/09d16ce53d4698eabf815a588e57d057edaf3f0e#diff-04c6e90faac2675aa89e2176d2eec7d8L36

**Comment by sebn** [comment]
> do you think this downliad link is discoverable enough?

I would prefer a Download link separate from the rest of the text (ideally similar to the one used in the Drive web app, but this could be improved later). Also having *Cozy Drive for Desktop's website* as the link label sound a bit confusing to me, isn't it actually the Cozy download page? Wouldn't *Download* as the link text just work?

> Do you know where I can find the official documentation that was linked here

No idea :confused: 

The rest of the diff is definitely an improvement regarding the current README!

**Comment by sebn** [comment]
**Off topic**: regarding the [Download page](https://cozy.io/en/download/):

- *Cozy Drive* is repeated a lot which doesn't help finding the relevant links
- Having sections per device followed by a section for another app (Banks) doesn't help figuring out how sections are organized

Wouldn't it help to have main sections per device, since one is generally mostly interested in its current device?
Should we open an issue for this? Wdyt?

**Comment by sebn** [comment]
Regarding the link to the documentation, I believe we should first organize the `doc/usage/` contents including some index page, make it available through GH pages and link there.

We can figure out how to integrate it into docs.cozy.io later. Wdyt?

**Comment by enguerran** [comment]
> I believe we should first organize the doc/usage/ contents including some index page, make it available through GH pages and link there.

That will be a second step to the enhancement of the technical (ie accessible through github) documentation.

**Comment by enguerran** [comment]
Now we are aligned, I will open the PR to make things happening in a more factual way. Thanks for your advices and tips.
