### ISSUE TITLE
Impossible to install cozy-desktop on Manjaro Cinnamon desktop - node.js

### ISSUE THREAD

**Issue by olielvewen** [cozy-labs/cozy-desktop#1371]
### Description

I would to install the community version (and then not the appimage) on my Manjaro distribution Cinnamon desktop. For this step I'm using the pamac gui tool. Other, I've run into an issue about dependencies because

### Steps to Reproduce

1. search and select cozy-desktop package in the pamac gui/octopi gui
2. the tool check the compatibility
3. Install is stopped because an message is explaining the reason which is the following (in french):

la satisfaction des dépendances a échoué:
la suppression de nodejs casse la dépendance « nodejs>=10 » requise par apm

### Expected behavior

Install like usual the cosy-desktop application. Like this I've get all update about the cosy-desktop version (and not with the appimage). Anyway, I don't like appimage, when that's works... 

### Actual behavior

nodejs seems to be removed and that breaks the package nodejs=>10

### Informations

* **reproductible**: install an Manjaro Cinnamon community version and update repo, sofware and then try to install the cosy-desktop package
* **OS**:GNU/Linux Manjaro Cinnamon
* **version**: Kernel: 4.19.12-2-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 
           Desktop: Cinnamon 4.0.8 info: cairo-dock wm: muffin dm: LightDM 1.28.0 
           Distro: Manjaro Linux

**Comment by sebn** [comment]
Hello @olielvewen, thank you for reporting this.

We don't maintain any distribution package yet, so I don't really know how this one was packaged.

Looking at [the package info](https://repology.org/metapackage/cozy-desktop/versions), I assume it was contributed by @ArchangeGabriel :)

@ArchangeGabriel sorry to bother you, but do you have any idea why this is happening?

**Comment by ArchangeGabriel** [comment]
`cozy-desktop` requires `nodejs 8.x`. Thus, it cannot be currently installed together with packages that requires newer version (in your case `apm`, and likely something else depending on it, likely `atom`). This will be solved when `cozy-desktop` will be upgraded to a newer nodejs version.

@sebn Yes, Manjaro is an Arch derivative, so most of their packages are Arch ones, including this one.

**Comment by olielvewen** [comment]
Hi.

Thanks a lot for looking at my issue.

Well, if I understand well, this issue comes from the version of nodejs (8.x) which is old. And this one is on conflict with others more "updated" like this one (in my case) used by one of my ide Atom.

I've done more search (i should do it before open an issue here ^_^) which confirm what ArchangeGabriel have explained above.
`[olivier@thorielle ~]$ pacman -Qi nodejs
Nom                      : nodejs
Version                  : 11.6.0-1
Description              : Evented I/O for V8 javascript
Architecture             : x86_64
URL                      : http://nodejs.org/
Licences                 : MIT
Groupes                  : --
Fournit                  : --
Dépend de                : openssl  zlib  icu  libuv  c-ares  libnghttp2
Dépendances opt.         : npm: nodejs package manager [installé]
Requis par               : apm  boostnote  grunt-cli  node-gyp  npm  semver
Optionnel pour           : --
Est en conflit avec      : --
Remplace                 : --
Taille installée         : 21,01 MiB
Paqueteur                : Felix Yan <felixonmars@archlinux.org>
Compilé le               : jeu. 27 déc. 2018 06:19:52 CET
Installé le              : lun. 31 déc. 2018 19:18:10 CET
Motif d’installation     : Installé comme dépendance d’un autre paquet
Script d’installation    : Non
Validé par               : Signature

[olivier@thorielle ~]$ pacman -Qi atom
Nom                      : atom
Version                  : 1.33.1-3
Description              : A hackable text editor for the 21st Century
Architecture             : x86_64
URL                      : https://github.com/atom/atom
Licences                 : MIT  custom
Groupes                  : --
Fournit                  : --
Dépend de                : apm  electron  libxkbfile
Dépendances opt.         : ctags: symbol indexing support
                           git: Git and GitHub integration [installé]
Requis par               : --
Optionnel pour           : --
Est en conflit avec      : --
Remplace                 : atom-editor
Taille installée         : 182,43 MiB
Paqueteur                : Nicola Squartini <tensor5@gmail.com>
Compilé le               : dim. 30 déc. 2018 19:07:24 CET
Installé le              : lun. 31 déc. 2018 19:18:13 CET
Motif d’installation     : Explicitement installé
Script d’installation    : Non
Validé par               : Signature

[olivier@thorielle ~]$ pacman -Qi apm
Nom                      : apm
Version                  : 2.1.3-2
Description              : Atom package manager
Architecture             : x86_64
URL                      : https://github.com/atom/apm
Licences                 : MIT
Groupes                  : --
Fournit                  : nodejs-atom-package-manager
Dépend de                : libsecret  nodejs>=10  npm  python2
Dépendances opt.         : --
Requis par               : atom
Optionnel pour           : --
Est en conflit avec      : nodejs-atom-package-manager
Remplace                 : nodejs-atom-package-manager
Taille installée         : 11,50 MiB
Paqueteur                : Felix Yan <felixonmars@archlinux.org>
Compilé le               : mer. 24 oct. 2018 20:23:50 CEST
Installé le              : mer. 31 oct. 2018 17:12:40 CET
Motif d’installation     : Installé comme dépendance d’un autre paquet
Script d’installation    : Non
Validé par               : Signature

[olivier@thorielle ~]$ 
`Well, I will wait an update than I hope soon of cozy-desktop. Thanks a lot.

**Comment by ArchangeGabriel** [comment]
Another interested person realized that it was running fine without node installed. @sebn Does cozy-desktop requires nodejs at runtime?

**Comment by nono** [comment]
@ArchangeGabriel the nodejs used by cozy-desktop at runtime is the one embedded in electron. So, you don't need to explicitly install nodejs to use cozy-desktop.

**Comment by ArchangeGabriel** [comment]
OK, perfect. So @olielvewen your issue is fixed, just try to install again. ;) And this ticket can be closed. :)

**Comment by olielvewen** [comment]
Okay. I'm going to try again. I'll said you in few minutes if all is okay.

**Comment by ArchangeGabriel** [comment]
Well actually in your case there might be a little delay before the package in synced from Arch to Manjaro. The fixed version is 3.11.2-2, you can manually download it from https://www.archlinux.org/packages/community/any/cozy-desktop/download/ at worst.

**Comment by olielvewen** [comment]
Effectively. Did you know how many time this operation will be done ? Just around, not exactly. ^_^

**Comment by ArchangeGabriel** [comment]
Absolutely no idea, I don’t even know if they sync manually (they do at least for some packages that they modify) or automatically, at which frequency, and so on.

**Comment by olielvewen** [comment]
I've sync my repos in command line and after I've tried to install cozy-desktop. 
I've got the following error. i'm not sure that the same event the result is the same. 
`[olivier@thorielle ~]$ yaourt -S cozy-desktop
résolution des dépendances…
recherche des conflits entre paquets…
:: nodejs-lts-carbon et nodejs sont en conflit. Supprimer nodejs ? [o/N] n
erreur : un conflit de paquets impossible à résoudre a été détecté
erreur : la préparation de la transaction a échoué (conflit de dépendances)
:: nodejs-lts-carbon et nodejs sont en conflit
 `
An idea perhaps ?

**Comment by ArchangeGabriel** [comment]
What you did is syncthing your local repo with a Manjaro mirror. What you need to do, is either wait for Manjaro repos to sync from Arch ones, or to download and install manually from my above link. ;)

**Comment by olielvewen** [comment]
Yes for the first.
So, even I can do it (and I have even download it), I will try tomorrow. The sync will be done and like this we will be sure that the issue will be down. 
And if all is great, I will told you tomorrow.
@demain.

**Comment by olielvewen** [comment]
Yesterday, after sync my repos, I've tried two times to install cozy-desktop package. I run into the same issue. 
node-lts-carbon is in conflict with node-js.

`[olivier@thorielle ~]$ sudo pacman -S cozy-desktop
résolution des dépendances…
recherche des conflits entre paquets…
:: nodejs-lts-carbon et nodejs sont en conflit. Supprimer nodejs ? [o/N] n
erreur : un conflit de paquets impossible à résoudre a été détecté
erreur : la préparation de la transaction a échoué (conflit de dépendances)
:: nodejs-lts-carbon et nodejs sont en conflit
[olivier@thorielle ~]$ pacman -Qi nodejs-lts-carbon
erreur : le paquet « nodejs-lts-carbon » n’a pas été trouvé

[olivier@thorielle ~]$ pacman -Qi nodejs
Nom                      : nodejs
Version                  : 11.6.0-1
Description              : Evented I/O for V8 javascript
Architecture             : x86_64
URL                      : http://nodejs.org/
Licences                 : MIT
Groupes                  : --
Fournit                  : --
Dépend de                : openssl  zlib  icu  libuv  c-ares  libnghttp2
Dépendances opt.         : npm: nodejs package manager [installé]
Requis par               : apm  boostnote  grunt-cli  node-gyp  npm  semver
Optionnel pour           : --
Est en conflit avec      : --
Remplace                 : --
Taille installée         : 21,01 MiB
Paqueteur                : Felix Yan <felixonmars@archlinux.org>
Compilé le               : jeu. 27 déc. 2018 06:19:52 CET
Installé le              : lun. 31 déc. 2018 19:18:10 CET
Motif d’installation     : Installé comme dépendance d’un autre paquet
Script d’installation    : Non
Validé par               : Signature

[olivier@thorielle ~]$ 
`

After searching a bit, node-lts-carbon is not packaged alone but it seems to be a part of node-js.

Today, I've updated another fresh Manjaro on another computer with the Deepin dekstop environment done mainly in QT5 and C++.
When I said Fresh, I've done none install of any kind of additional software like I do after an fresh install ex Geany, Atom, Boostnote...
This desktop has been just updated.
I've got the same issue and I've not even Atom, Boostnote, installed and even any others electron applications.

**Comment by ArchangeGabriel** [comment]
Indeed, Manjaro repos still did not sync with ArchLinux ones. See that here for instance: https://repology.org/metapackage/cozy-desktop/versions. Manjaro doesn’t even have the `3.11.2` version yet, so `3.11.2-2` is likely even further away.

**Comment by olielvewen** [comment]
Effectively. Like I'm in stable, I prefer to wait.
Fortunately, we won't wait for a while like we are on Arch (and then derivated) system.

I'll keep you inform from the result soon it will be done. Thanks. Crossed fingers.

**Comment by olielvewen** [comment]
Hi,
Yesterday, we have had a big update and I've been able to install cozy-desktop on the both PC's.

Just one thing: There are something a bit annoying because Electron 2 is installed too. To be precise the version v2.0.16.
Either I 've already installed the last version of Electron on my computer and it is the v 3.0.13. So, I've the both version.

I'm waiting your answer about this "issue" and after I will close this bug.
BTW Thanks a lot again.

**Comment by olielvewen** [comment]
I close this bug. However, I note a display bug. Firstly, the Electron2 is running and displaying when I start an new session and we can see too an adempt to display cozy in the middle of the screen. Closing Electron and clicking on the cozy icon resolve this issue. Unfortunately, my screenshot has not been saved. Anyway, I will open another issue for that.
About this issue, for me all is fine. We can now install cozy-desktop. 
Thanks a lot. And great work.
