### ISSUE TITLE
Cozy-desktop is in the middle of the desktop at the startup in a blank window

### ISSUE THREAD

**Issue by olielvewen** [cozy-labs/cozy-desktop#1425]
### Description

When I run my computer, Electron window 2.0 appear and behind, in the middle of the screen we can see cozy-desktop in a blank window. Closing electron window close her and clicking on the cozy icon in the systray do desapear the blank window in the middle of the screen.

### Steps to Reproduce

1. Get an Manjaro desktop with the environment of your choice (for me on Cinnamon and Deepin)
2. **run cozy-destop automatically at the startup**
3. reboot and look...

### Expected behavior

No Electron 2.0 window and no blank screen in the desktop

### Actual behavior
When I run my computer, Electron window 2.0 appear and behind, in the middle of the screen we can see cozy-desktop in a blank window. Closing electron window close her and clicking on the cozy icon in the systray do desapear the blank window in the middle of the screen.
See this screenshot : http://pix.toile-libre.org/?img=1548511053.png

### Informations

* **reproductible**: Always
* **OS**: GNU/Linux Manjaro Cinnamon
* **version**:   
version: Kernel: 4.19.12-2-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1
Desktop: Cinnamon 4.0.8 info: cairo-dock wm: muffin dm: LightDM 1.28.0
Distro: Manjaro Linux

**Comment by whiver** [comment]
Same for me under Ubuntu 18.10 with Gnome desktop, and after some time (~5 min) the window become normal.

**Comment by ALB5** [comment]
Same bug on Ubuntu 19.04. 
I am paid user, if it does not get fixed soon, I will move to another more reliable tool.

**Comment by olielvewen** [comment]
With the version 3.14 on Cinnamon and on Deepin, this bug is resolved. Hovewer, the blank screen is still present only and always on Cinnamon. I've used several kernel (now 5.2.8-1).  since I've reported this bug and the bug was present until this last update. what pleasure to not see this electron window.
The version of Cinnamon is the 4.2.3.

**Comment by taratatach** [comment]
Hi. The blank window issue should be resolved by #1694 which will soon be shipped in the next release.
We're really glad the Electron window issue is finally resolved :).

**Comment by taratatach** [comment]
The fix for the empty window has been released: [https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.15.0](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.15.0).

Since the other issue with the Electron window is fixed as well, I'm closing this issue.

**Comment by olielvewen** [comment]
Thanks a lot. I look forward to this new version which should not to be late on Manjaro.

**Comment by olielvewen** [comment]
I have updated the cozy app yesterday and now he is in the version 3.15.0.
And I confirm that the empty window has disappeared. 
Great work.
