### ISSUE TITLE
linux client eats up disk I/O

### ISSUE THREAD

**Issue by VilainMamuth** [cozy-labs/cozy-desktop#1534]
### Description

When the client syncs, it eats up all the i/o. The system slows down and impacts user experience.

### Steps to Reproduce
With autostartup set up
1. Open a user session
2. launch firefox
3. wait :(

### Expected behavior

The sync should have less I/O priority. 
Maybe using ionice -c 3 when setting the autostart command?

### Informations

* **reproductible**: always
* **OS**: Ubuntu 19.04 
* **version**: 3.12.0

1100 files : ~ 2GB to sync

**Comment by whiver** [comment]
I confirm, same thing for me. I end up disabling the autostart of Cozy on logon as it causes random freezes while it's in "Preparing" state.
It takes around 7GB to sync on my side (and around 250MB of ram after the sync, it's quite a lot for an idle state).
![image](https://user-images.githubusercontent.com/394565/76162227-8fae1b80-6133-11ea-9b01-d826b3cb22bc.png)

**Comment by taratatach** [comment]
This should be addressed by the [latest release](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.41.0).
