### ISSUE TITLE
Window empty at start on Ubuntu

### ISSUE THREAD

**Issue by AZn5ReD** [cozy-labs/cozy-desktop#1693]
### Description

When starting the client, the window is empty. The workaround is to minimize the window and the open it again afterwards. I tried to start with the --hidden flag, but it doesn't change anything.

### Steps to Reproduce

1. ./CozyDrive-3.14.0-x86_64.AppImage

### Expected behavior

With the --hidden flag, the window should not appear ?
Without it, the window should show the list of the recent files, etc.

### Actual behavior

The window is empty at start.
![image](https://user-images.githubusercontent.com/1781837/63475725-691de100-c47e-11e9-86b4-fbccf8a51f94.png)

### Informations

* **reproductible**: Always
* **OS**: Ubuntu
* **version**: 18.04.3

**Comment by taratatach** [comment]
Hi @AZn5ReD, thank you for reporting this issue.

This is in fact a known issue and we shouldn't be showing any window on startup, just the icon in the systray.
This should be fixed by #1694 when released.

By the way, Cozy Desktop does not accept any `--hidden` flag.

**Comment by taratatach** [comment]
The fix has been released: [https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.15.0](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.15.0).
