### ISSUE TITLE
 UnhandledPromiseRejectionWarning Cannot find module '../build/Debug/watcher.node'

### ISSUE THREAD

**Issue by jiawanyovan** [cozy-labs/cozy-desktop#1752]
### Description
UnhandledPromiseRejectionWarning is displayed with a note that something is missing " Error: Cannot find module '../build/Debug/watcher.node' "

[Description of the bug or feature]
Nothing is syncing and the Cozy Drive is empty. 
My uname --all returns following: 
Linux worldhost.nodomain 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

1.Either,  chmod 760 Cozy-Drive-3.16.0-x86_x64.AppImage 
   or,  chmod +x Cozy-Drive-3.16.0-x86_x64.AppImage 
2. Run ./Cozy-Drive-3.16.0-x86_x64.AppImage
3. Enter personal address : dummy.mycozy.cloud
4. Enter password
5. Enter 2FA code in personal email 
6. Following message is seen:

(node:12003) UnhandledPromiseRejectionWarning: Error: Cannot find module '../build/Debug/watcher.node'
Require stack:
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/binding.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/native-watcher.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/path-watcher-manager.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/index.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/core/local/atom/producer.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/core/local/atom/watcher.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/core/local/watcher.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/core/local/index.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/core/app.js
- /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/gui/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (/tmp/.mount_Cozy-DNo3LIx/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at getWatcher (/tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/binding.js:9:17)
    at Object.watch (/tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/binding.js:105:12)
    at channel (/tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/native-watcher.js:64:15)
    at NativeWatcher.start (/tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/native-watcher.js:63:26)
    at NativeWatcher.onDidChange (/tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/native-watcher.js:102:10)
    at PathWatcher.onDidChange (/tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/path-watcher.js:158:31)
    at /tmp/.mount_Cozy-DNo3LIx/resources/app.asar/node_modules/@atom/watcher/lib/path-watcher.js:167:14
(node:12003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12003) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 
7. Cozy Drive icon is shown as "syncing" with no files in actual downloading or uploading action 

### Expected behavior

Cozy Drive, after logging in to my account, will have all files in the cloud downloaded and syncing normally like in Dropbox, MEGAsync or pCloud. Cozy Drive has worked on Ubuntu 18.04 and Fedora 31.

### Actual behavior

Cozy Drive has remained in "syncing" action, No files is uploaded or downloaded from local Cozy Drive.

### Informations

* **reproductible**: Always
* **OS**: Centos 7 with encrypted hard drive password before bootstrapping
* **version**: Cozy-Drive-3.16.0-x86_x64

**Comment by taratatach** [comment]
Hi @jiawanyovan,

thank you reporting this issue but we don't really use github issues for support. I encourage you to reach out on our forum at https://forum.cozy.io or even better for such issues, via the contact form within the app itself (`Preferences` tab > `Send us a message`) which will attach debugging logs to your message.

**Comment by jiawanyovan** [comment]
ok noted. Have a nice weekend

**Comment by taratatach** [comment]
I'm closing this issue since we'll handle it via support.
