### ISSUE TITLE
Merge error

### ISSUE THREAD

**Issue by wysow** [cozy-labs/cozy-desktop#1817]
### Description

Hello,

I'm facing a problem (maybe a bug) when trying to synchronize my drive.
 
### Steps to Reproduce

1. Launching Mac Cozy Drive app
2. Waiting end of synchronization

### Expected behavior

Complete synchronization.

### Actual behavior

Getting "incomplete synchronization" message

### Informations

Getting this in the logs:

```json
{
    "name": "Cozy Desktop",
    "hostname": "MacBook-Pro-de-Gaultier.local",
    "pid": 92653,
    "component": "Sync",
    "level": 50,
    "err": {
        "message": "Cannot merge remote change: Missing parent metadata",
        "name": "MergeMissingParentError",
        "stack": "MergeMissingParentError: Cannot merge remote change: Missing parent metadata\n    at Merge.ensureParentExistAsync (/Applications/Cozy Drive.app/Contents/Resources/app.asar/core/merge.js:115:13)"
    },
    "msg": "Could not start watchers",
    "time": "2020-02-18T19:57:14.371Z",
    "v": 0
}
```

* **reproductible**: always
* **OS**: macOS
* **version**: 3.18.0

**Comment by taratatach** [comment]
Hi @wysow,

thanks for reaching out. I invite you to contact our support via the application itself (`Preferences` tab > `Send us a message`). Some application log files will be attached to your message and will help us identify the issue you're facing.

You can also send us an e-mail at contact@cozycloud.cc if you prefer.

I'm closing this issue as the error you're facing is a symptom of other issues and we'll need your log files to debug.

Erwan

**Comment by wysow** [comment]
@taratatach thanks for the quick reply, just sent a message in the app.
