### ISSUE TITLE
Mail for Amazon synchronisation not coming

### ISSUE THREAD

**Issue by fujisan43** [cozy-labs/cozy-desktop#1835]
### Description

I want to synchronize my amazon account.
After  entering my email address and my password of my amazon account, I need to enter a code that I am supposed to receive by email. But that mail never comes.
So i'm unable to synchronize my amazon account

### Informations

* **reproductible**: always
* **OS**: windows 10 pro

**Comment by taratatach** [comment]
Hi @fujisan43.

This project is the desktop client to synchronize the files on your Cozy with your computer.
It seems you're experiencing some issues with the Amazon connector so I invite you to send us a message at contact@cozycloud.cc.

Sorry for the delay but github issues are not monitored as closely as support requests.

Have a nice day,
Erwan
