### ISSUE TITLE
Electron version

### ISSUE THREAD

**Issue by ArchangeGabriel** [cozy-labs/cozy-desktop#1915]
Hi there,

Electron version used is lagging behind again. Electron 5.x support ended in late 2019, 6.x support also ended since, and 7.x is going to be endeed soon. Is there any plan to migrate to newer Electron versions?

Thanks!

**Comment by taratatach** [comment]
Hi @ArchangeGabriel.

The upgrade is planned to start this week. It will probably take some time but our goal is to catch up with the latest version.

**Comment by ArchangeGabriel** [comment]
I have seen that you already managed to move to electron 9.x, congrats on this! Do you plan to move up to electron 10 for the coming release or not? We (Arch Linux) are still on 9.x currently, but in the process of moving towards 10.x.

**Comment by ArchangeGabriel** [comment]
That’s OK, I’m now shipping electron9 and cozy-desktop 3.23.0 built against it.

**Comment by ArchangeGabriel** [comment]
The latest release upgraded to 11.x, congratulations for that! Hopefully it will be easier for you to keep up-to-date now. ;)

**Comment by taratatach** [comment]
It's always an on-going process. We'll pretty much always be a bit behind but I try to stay as up-to-date as possible ;-)
