### ISSUE TITLE
[New Feature] Support for multiple account on the same desktop

### ISSUE THREAD

**Issue by cvinh** [cozy-labs/cozy-desktop#2259]
### Description

I have several cozy accounts (for different companies that I manage) but I have only one computer.
Actually, it seems that it's not possible to manage several accounts on the same desktop.

### Steps to Reproduce

N/A

### Expected behavior

I would like to manage my several cozy accounts with different shared folders on the same desktop

### Actual behavior

N/A

### Informations

* **reproductible**: Always new feature
* **OS**: GNU/Linux (Fedora)
* **version**: [you can find it in the settings tab]

**Comment by clochix** [comment]
Hello @cvinh,

This is not a feature we plan to add. Using several Cozy accounts is not a use case we considered when we started to develop the application.
Adding such a feature would require a huge amount of work, and is not on our roadmap.

Could you please send an email to claude at cozycloud.cc (we speak french ;-) ) detailing your use case. Maybe we could find some kind of hack.

**Comment by cvinh** [comment]
Merci
