### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by JustinsKittens** [cozy-labs/cozy-desktop#2267]
### Description

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Steps to Reproduce

1. Go to the [self build documentation page](http://cozy-labs.github.io/cozy-desktop/doc/usage/build.html)
2. Copy 'git clone git@github.com:cozy-labs/cozy-desktop.git'
3. Paste it into a terminal and press enter

### Expected behavior

For the source code to be copied into my file system.

### Actual behavior

Error, stating:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Informations

* **Always**
* **Replit (20.04.2 LTS)**
* **v3.36.1**

**Comment by Crash--** [comment]
Hi @JustinsKittens! 

Thanks for reporting this issue. This is an issue with your ssh agent and github. If you want to use `git clone git@github.com` syntax, you should add your public key to your github account. https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey#verify-the-public-key-is-attached-to-your-account 

If you don't have configured ssh on your github action, can you try to clone overs https with 
```
git clone https://github.com/cozy-labs/cozy-desktop.git
```

**Comment by lacthon** [comment]
Can i work on the issue

**Comment by taratatach** [comment]
Hi @lacthon. The issue lies in @JustinsKittens's Github config so I don't see any way you could help with that.
I'm closing the issue.

@JustinsKittens feel free to open a new issue if you believe there is something else.
