### ISSUE TITLE
[appimage] 3.38 beta2 crash

### ISSUE THREAD

**Issue by skramm** [cozy-labs/cozy-desktop#2295]
### Description

Happy user here (until this morning).
The app suddenly crashes, had been working fine for days/month.
Crash, then unable to start again.

I had a similar issue with 3.37 (cf. your mail from 22/03), escaped it by reverting to 3.36, but after an update, I got 3.38 installed (sorry, can't remember when that update happened...)

Making an attempt to start it from command line, I get this:
(no idea what this "badly formated URL" thing is)

```
$ /mnt/data/INSTALL_FILES/Cozy-Drive-3.38.0-beta.2-x86_64.AppImage --hidden
FAIL TO SETUP Error: badly formated URL
    at toSentryContext (/tmp/.mount_Cozy-DX2rMc9/resources/app.asar/core/utils/sentry.js:53:20)
    at Object.setup (/tmp/.mount_Cozy-DX2rMc9/resources/app.asar/core/utils/sentry.js:71:47)
    at Object.<anonymous> (/tmp/.mount_Cozy-DX2rMc9/resources/app.asar/gui/main.js:69:8)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at node:electron/js2c/browser_init:2:115363
    at node:electron/js2c/browser_init:2:115566
    at node:electron/js2c/browser_init:2:115570
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/loaders:331:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/loaders:269:10)
    at loadBuiltinModule (node:internal/modules/cjs/helpers:50:9)
    at Module._load (node:internal/modules/cjs/loader:862:15)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
```
Additional info:
```
$ uname -a
Linux sk-Latitude-E6540 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

I'll try reverting to 3.36, I'll let you know

**Comment by skramm** [comment]
Confirmation: No problem with 3.36.1-beta2 AppImage, everything ok.

**Comment by taratatach** [comment]
Hi @skramm. The error displayed above is harmless and would not prevent the app from running.
Sadly, I don't have enough information to help you here.
It would be best to contact our support with app logs (send an e-mail to support at cozycloud dot cc).

Out of curiosity, why did you choose `v3.36.1-beta.2` over `v3.36.1`?

**Comment by skramm** [comment]
Hi @taratatach 
I don't get it  (but maybe I wasn't clear): the app crashes on startup, and that error would not prevent the app from running?
>Out of curiosity, why did you choose v3.36.1-beta.2 over v3.36.1?

Oh, just some dumb error of mine, should have use the other one, sure.

Ok, I'll make another try with 3.38 and email support (strange way to handle app issues, but... whatever). Could you tell me if there is some verbose option I can add to launch, that could maybe help diagnosis?

**Comment by taratatach** [comment]
> I don't get it (but maybe I wasn't clear): the app crashes on startup, and that error would not prevent the app from running?

Yes, that's what I meant.

> Ok, I'll make another try with 3.38 and email support (strange way to handle app issues, but... whatever)

App logs contain data that you probably don't want to be public (e.g. file paths). This is why we do support in a more private manner.

There is no verbose mode.

**Comment by skramm** [comment]
ok, got it, thks!

**Comment by skramm** [comment]
Some mystery here: did exactly the same as above (CLI start) with 3.38.0 beta2 and now no crash...
I must say I did a reboot in the meanwhile (I frequently have an uptime of several days/weeks), so maybe it was an issue with my machine.
I assume I can close this... And thanks to you guys for that great thing!
