### ISSUE TITLE
🖥️ DESKTOP - Electron 23 has been EOL for some time

### ISSUE THREAD

**Issue by alerque** [cozy-labs/cozy-desktop#2334]
Electron 23, used in the last tagged release of this project, was [marked EOF six months ago](https://releases.electronjs.org/release/v23.3.13). The current version in Electron 29.

I am the Arch Linux packager for Electron and we're trying to drop all the EOL versions. This is the last app keeping us having to build and support Electron 23.

Please make it a priority to keep current releases using at least some supported version of Electron. This is a significant pain point for downstream packagers.

**Comment by alerque** [comment]
Ping. There is starting to be a real chance not addressing this is going to get Cozy Desktop booted from official packaging repositories for Arch Linux. This would be a step down for your end users convenience. If you don't want that to happen please cut a release that builds with a currently supported version of Electron (for longevity of course jumping all the way to 30 would be best at this point).

**Comment by captn3m0** [comment]
IMO, packages including known vulnerable software should not be included beyond a small warning period (1 month?) in the official repos.

**Comment by Strit** [comment]
It least it seems to be worked on....

https://github.com/cozy-labs/cozy-desktop/pull/2345

**Comment by taratatach** [comment]
Hi. Sorry about the delay but we add some difficulties to migrate to a recent version.
It's done in the [latest release](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.41.0). We're now using Electron v31.
