### ISSUE TITLE
where shoud be .cozyignore ?

### ISSUE THREAD

**Issue by pierrerousseau** [cozy-labs/cozy-desktop#248]
When I read that it .cozyignore was working like .gitignore, I put it into my synchronized folder ... but it did not work. I figured out that I had to put it in my home directory. Is there a reason for that ? If not, what about puting into the synchronized folder ? If yes, I think that the documentation should be clear on that.
Thanks for the work, it seems to be working already!

**Comment by nono** [comment]
It should work when the `.cozyignore` is in the synchronized folder. So, it's probably a bug. I'll look at it soon.

**Comment by nono** [comment]
I confirm: it was a bug.

**Comment by pierrerousseau** [comment]
Ok waiting for the merge! :+1:
