### ISSUE TITLE
Small UI improvements on the onboarding

### ISSUE THREAD

**Issue by pierrevdk** [cozy-labs/cozy-desktop#364]
The on-boarding is awesome! These are just few details:

@nono On the second screen would it be possible to have an example in the form imput (like cozyxxx.cozycloud.cc)? I was going to put my email address, as it is the case in every other on-boarding process.

@kelukelu About those link just above the big button (like "Don't have an account? Request one") could it be possible to underline them, at least when hovering them? It would be tremendously better in terms of accessibility.

And maybe a go back button, sometimes you press Next too fast.

My two cents :)

**Comment by nono** [comment]
I think it was fixed
