### ISSUE TITLE
Show download progress

### ISSUE THREAD

**Issue by frankrousseau** [cozy-labs/cozy-desktop#37]
When a file is downloaded no progress is displayed.

**Comment by pierrerousseau** [comment]
Are you sure ? In the cli version i saw no progress or information, just "blabla download" or "put blabla"

**Comment by nono** [comment]
The CLI had some progress bars but they were removed.

**Comment by pierrerousseau** [comment]
A message saying that the process is now waiting could be useful, I though something went wrong when node stopped to work (ok, I had a crash a few mins before due to my computer so my state of mind was probably wrong ... but still).

**Comment by nono** [comment]
Sure, we will improve the CLI experience. It's just not the current priority. Right now, we are working on making the synchronization more reliable and having a basic GUI with electron.

**Comment by nono** [comment]
The progress bar for downloads/uploads has been added back in the just release v0.10.0.
