### ISSUE TITLE
No icon is displayed in the "notification center" of Debian Jessie

### ISSUE THREAD

**Issue by roukydesbois** [cozy-labs/cozy-desktop#422]
The icon for cozy-desktop is not displayed in the notification bar on the bottom in Jessie:

![notif bar jessie](https://cloud.githubusercontent.com/assets/11874580/17394327/ceebf53a-5a28-11e6-8a2c-1ee6dd5badce.png)

It is still clickable and cozy-desktop appears when clicking between the two displayed icons, yet no image is displayed.

**Comment by nono** [comment]
Hi, we know that in some conditions in the icon is not displayed (or it flicks) but it's hard to test every distributions and window manager to find where. So, it's nice to have feedbacks from our users. Thanks!

**Comment by sebn** [comment]
Hello there!
Sorry for the late answer.

Are you still getting this issue?
And can you tell me which version of Debian / GNOME you're using?
And did you install any GNOME shell extension?

Thank you!

**Comment by drigorsebesta** [comment]
Hi, 

I have the same problem, but sometimes the icon appears (most of the time not).
I'm using Debian 8 Jessie with Gnome 3.14.1 .
Yes there are extensions installed (extensions which are by default installed), but not activated.

**Comment by Romdef** [comment]
Hi there,
The same for me on elementary OS 0.4.1.
No icon in the wingpanel ... it worked when Cozy was launched in January.

**Comment by sebn** [comment]
We're a bit stuck on this one: last time I gave it a try on a stock Debian Jessie, it was working.

Also @Romdef, although Elementary OS is based on GNOME, it seems quite different, using its own UI components for task switching & the dock. So it may be yet another issue.

**Comment by sebn** [comment]
Hello there, I'll be closing this one because I doubt we'll fix it since Jessie is an old stable release and we lack the manpower to handle all the GNU/Linux options out there.

In case you're using the latest stable Debian release (9.0 stretch), or a fork of the latter, and still encoutering the issue, feel free to open a separate issue and link to this one.
