### ISSUE TITLE
Calender & Contacts viewing FEATURE

### ISSUE THREAD

**Issue by 2SI3NX** [cozy-labs/cozy-desktop#435]
Minimizing this in the Ubuntu Taskbar, it would be nice having notifications of your next appointment and viewing and editing your calender, as well as contacts!!  This would really be useful im sure of it!

Any thoughts?

**Comment by nono** [comment]
Hi,
thanks for the suggestion. It's a cool idea. Currently, I have a lot of stuff to do before that (like support for OSX and windows), but if someone wants to contribute, I can help him/her.

**Comment by Beast141** [comment]
ok cool thanks!  Hope someone can help with this!

**Comment by sebn** [comment]
Hello there!

A contacts Web app is currently being implemented. A calendar Web app should follow at some point (may take some time though), and hopefully contact and calendar syncing. Whether the syncing will be done through the desktop app or another way is still being discussed.

In the end, users should be able to edit their synchronized contacts either in some native app or in the web app. Same for their calendars. But having notifications for users not using native apps makes sense, thank you for pointing this out! Launching the web apps easily from the desktop tray menu is planned too.

@2SI3NX Do you think the desktop client should provide more integration than what I described above?
