### ISSUE TITLE
cozy-desktop prints lots of stack traces without any error

### ISSUE THREAD

**Issue by thblt** [cozy-labs/cozy-desktop#443]
On an up-to-date Archlinux, using cozy-desktop installed with `npm install cozy-desktop -g`, when I invoke cozy-desktop (even without parameters, or with `--help`), it prints two deprecation warnings:

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release. 
```

then dumps a gigantic amount of stack traces to stdout before printing anything.  As an exemple, here's the  355kb [stderr output](https://github.com/cozy-labs/cozy-desktop/files/476927/stderr.txt) I get when I run `cozy-desktop --help`. It's 1984 lines for 355144 characters (!!!).  After that, cozy-desktop nicely displays its help screen.

Notice this is a purely cosmetic problem: I haven't experienced any actual problems using the CLI client.

**Comment by nono** [comment]
Hi @thblt,

thanks for the bug report.

It looks like the warnings come from leveldown, which is a dependency of a dependency (cozy-desktop -> pouchdb -> leveldown). We are strict on the version numbers for our direct dependencies. Maybe we should go to shrinkwrap to also force the version numbers for our indirect dependencies.

By the way, which version of nodejs do you use?

**Comment by thblt** [comment]
Thanks for the quick answer! That's NodeJS 6.6.0, it's the standard ArchLinux version (community/nodejs)

**Comment by thblt** [comment]
Just installed the git version as advised on #452, and it seems to fix this.  Closing?

**Comment by nono** [comment]
OK, thanks!
