### ISSUE TITLE
Name or password is incorrect.

### ISSUE THREAD

**Issue by JeromeDesseaux** [cozy-labs/cozy-desktop#471]
Bonjour, 

Quand j'essaie de me connecter avec Cozy Desktop: j'ai l'erreur suivante: Name or password is incorrect. 

J'ai installé un certificat letsencrypt sur nginx et pourtant, l'url dans la configuration arrive bien sur mon serveur et mon mdp est le bon (j'en suis certain ^^) 

NB: le client android fonctionne parfaitement avec les mêmes paramètres 

Est-ce un bug ou bien j'ai loupé quelque chose?

Merci pour votre aide!

**Comment by nono** [comment]
Bonjour,

l'erreur ne concerne pas le certificat letsencrypt (c'est un autre message d'erreur), mais bien la partie authentification.

À quelle étape intervient cette erreur ? Sur l'écran de saisie du mot de passe ?

Le client desktop écrit des logs dans le fichier `~/.config-desktop`. Est-ce qu'il serait possible d'envoyer ses logs à  log-desktop CHEZ cozycloud POINT cc ?

**Comment by sebn** [comment]
Bonjour,

@JeromeDesseaux rencontrez-vous toujours ce problème ?
Avez-vous besoin d'aide ?

**Comment by JeromeDesseaux** [comment]
Désolé de vous répondre si tard. Mais la solution a été simple: j'ai arrêter d'utiliser Cozy. 

Pour vous permettre de comprendre pourquoi : 
- La synchro automatisée avec mon téléphone fonctionnait une fois sur deux (contacts et photos). C'est assez lourd quand on essaie déjà de se soustraire à l'empire Google. 
- Impossible d'utiliser le client Android avec un certificat SSL Letsencrypt
- Impossible de me connecter avec un certificat SSL
- Aucun partage de fichier avec le FS. Si je perds ma BD qui est stockée sur un disque physique, je perds tout.

Voilà pour mes quelques retours. L'idée est bonne et je vous souhaite bonne chance dans votre aventure. Je serais heureux d'y revenir plus tard, quand ça fonctionnera mieux... 

Désolé de cette mauvaise nouvelle

**Comment by sebn** [comment]
Merci d'avoir pris le temps de répondre.
Je comprends, et je suis désolé pour les problèmes rencontrés.

Quelques questions ci-dessous, mais ne vous sentez pas obligé d'y répondre si vous n'avez pas le temps :

> La synchro automatisée avec mon téléphone fonctionnait une fois sur deux (contacts et photos)

Je voudrais remonter le problème côté mobile, mais la version Android, éventuelle ROM personnalisée, et si vous vous en rappellez la version de l'application Cozy me seraient utiles.

> Impossible d'utiliser le client Android avec un certificat SSL Letsencrypt
> Impossible de me connecter avec un certificat SSL

Serait-il possible de nous envoyer par mail (adresse [en bas de page](http://cozy.io/fr/)) le nom de domaine concerné, afin que nous puissions inspecter le certificat en question ?
J'utilise moi-même un certificat Letsencrypt et ne rencontre aucun problème avec SSL (desktop et android), ça nous aiderait à comprendre le problème et à le corriger.

> Aucun partage de fichier avec le FS

Est-ce que la nouvelle architecture [résoudrait le problème](https://github.com/cozy/cozy-stack/blob/master/docs/architecture.md#virtual-file-system-files) pour vous ?

> Je serais heureux d'y revenir plus tard, quand ça fonctionnera mieux

La [feuille de route de Cozy v3](https://blog.cozycloud.cc/post/2016/11/21/En-route-vers-Cozy-version-3) (en fin de l'article) peut vous donner une idée du bon moment pour retester Cozy si vous le souhaitez.

**Comment by JeromeDesseaux** [comment]
Aucun problème. Si ça peut vous aider et permettre d'avancer vers une solution 100% cocorico je suis pour :) 

1. J'utilise un Huawei Honor 5C avec sa surcouche officielle d'Android 6 et la version 2.1.0 de Cozy Mobile. Les fichiers (photos notamment) et contacts n'étaient pas synchronisés automatiquement. Obligé de forcer la syncho manuellement pour que ça fonctionne.
2. Je vous envoie par e-mail le nom de domaine concerné. Ainsi qu'un lien vers ce topic pour resituer le problème. J'utilise un raspberryPI chez moi avec un simple nginx avec un certificat let's encrypt le tout derrière un domaine no-ip.
3. Pour être honnête, je ne connais pas (ou presque pas) le quart des technologies affichées dans ces diagrammes. A partir du moment où mes fichiers sont stockés physiquement sur un FS et non dans une BD, ça me va. Exactement comme le fait ce que j'utilise actuellement : Nextcloud. Si jamais le serveur plante pour X ou Y raison, je peux toujours accéder à mes fichiers sur le FS du disque dur externe sur lequel il est branché. Le tout étant branché sur un NAS en réseau privé. Je peux donc accéder aux fichiers de mon cloud depuis chez moi sans avoir à passer par le réseau exterieur.

En tout cas merci de prendre le temps d'écouter ces quelques remarques et d'y prêter attention. 

Bon courage!
