### ISSUE TITLE
VersionEye says some dependencies have no license

### ISSUE THREAD

**Issue by sebn** [cozy-labs/cozy-desktop#481]
Dependencies reported in #480 :
- [ ] [progress]()
- [x] [pouchdb-server](https://www.npmjs.com/package/pouchdb-server)

The last one is [not yet reported on master](https://www.versioneye.com/user/projects/58541beead9aa20037389fff?child=summary#tab-licenses). Looks like VersionEye only reports issues on changed code after being set up.

Regarding `progress`, the issue is already fixed [in master](https://github.com/visionmedia/node-progress/blob/master/package.json#L21). Looks like a new version may be released [soon](https://github.com/visionmedia/node-progress/issues/134#issuecomment-267806369).

Regarding `pouchdb-server`, [PR here](https://github.com/pouchdb/pouchdb-server/pull/160)

Other dependencies will be fixed when reported as an issue.

**Comment by clochix** [comment]
Hello @sebn,

Thanks a lot for contributing to Cozy ☺

Ping @nono, could you please answer this user request.

**Comment by sebn** [comment]
The pouchdb-server version on master has the required fix.
But still no release of progress.
