### ISSUE TITLE
Do not reupload moved file, when created remotely

### ISSUE THREAD

**Issue by Kloadut** [cozy-labs/cozy-desktop#51]
When a file has been added remotely, it does not have a checksum.

Consequently, when it is moved locally for the first time, it is reuploaded.

**Comment by nono** [comment]
Now, when a file is added remotely, a checksum is computed by the cozy-files app. So, the file is not reuploaded when it is moved locally.

**Comment by nono** [comment]
Well, I've been too quick to close this issue. The checksum is added for files uploaded via files, but not for files fetched by the konnectors.

**Comment by aenario** [comment]
Note : If it helps, couchdb provides a md5 hash of the file
```
{
  "_id": "0077DD90-8149-C972-A259-D635CCB77428",
  "_rev": "2-27cefe17e69e08fd459808d9d24c4f81",
  "docType": "Binary",
  "_attachments": {
    "file": {
      "content_type": "image/jpeg",
      "revpos": 2,
      "digest": "md5-ekuz4cTSNmEtMZ+091FQPw==",
      "length": 409999,
      "stub": true
    }
  }
}
```

**Comment by nono** [comment]
It has been fixed.
