### ISSUE TITLE
binary is blank

### ISSUE THREAD

**Issue by 001101** [cozy-labs/cozy-desktop#533]
next issue

```bash
Uploading admin.2017-02-14.tar [===================-----------] 64% 260.1s

[2017-02-19 13:29:46:528] error - Synchronize    | Error: Binary is blank
    at /usr/lib/node_modules/cozy-desktop/lib/remote/index.js:117:29
    at /usr/lib/node_modules/cozy-desktop/node_modules/pouchdb/lib/index.js:119:11
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
```

**Comment by sebn** [comment]
Hello again :)

This one is definitively a cozy-desktop issue, although it's probably related to #532.

Could you temporarily move the `admin.2017-02-14.tar` file out of your Cozy folder until issue #532 is resolved, and tell me whether your other files are uploaded correctly?

**Comment by 001101** [comment]
other small files worked correctly and with 1.5GB files it's also working now, without making any changes on configs.

**Comment by sebn** [comment]
Nice, thanks!
