### ISSUE TITLE
Syncthing Synchronization Protocol

### ISSUE THREAD

**Issue by frankrousseau** [cozy-labs/cozy-desktop#78]
Here is the sync protocol described by Syncthing. It could be a good idea at some point to follow it. So Cozy would be compatible with @syncthing.

https://github.com/syncthing/specs/blob/master/BEPv1.md

**Comment by FromBabylon** [comment]
It would be awesome ! 
But the fact that [cozy stores files in database](https://forum.cozy.io/t/synchro-cozy-cloud-systeme-de-fichiers/317) isn't a problem ?

**Comment by frankrousseau** [comment]
Thank you @FromBabylon for your input. To be honest I don't know, it's a communication protocol. So, it shouldn't be a problem.

**Comment by nono** [comment]
Cozy-desktop works by using a continuous watch of files and couchdb capacities. Syncthing has a very different behaviour: from times to times, it walks the files tree and send these metadata on the network. The other sides check if he has differences and ask for the content of new files (in short).

If we want to support syncthing, it should be a new project. I think that most code of cozy-desktop won't help for this.
