### ISSUE TITLE
Whitelist tray icon in Ubuntu 13.10+

### ISSUE THREAD

**Issue by Kloadut** [cozy-labs/cozy-desktop#79]
Right now, the Cozy Desktop tray icon is not visible in the notification bar (top-right corner of the screen) in Ubuntu 13.10+.

This is related to a "whitelist" system introduced on Ubuntu 13.10+

See http://askubuntu.com/questions/30742/how-do-i-access-and-enable-more-icons-to-be-in-the-system-tray

**Comment by frankrousseau** [comment]
I think we can support only LTS.
