### ISSUE TITLE
Can't get stuff installed

### ISSUE THREAD

**Issue by FromBabylon** [cozy-labs/cozy-desktop#80]
It's been a while I am trying to install cozy-desktop on OSX. 
I installed node (but don't know how to install 'build-essentatials' on OSX).
Everything goes fine untill I launch cozy-desktop sync which stays at "info - Remote watcher | Start building your filesystem on your device." 
At this point I can see my device on my cozy cloud

Then after installing GUI, and after 'node_modules/.bin/gulp leveldown' the command cozy-desktop sync do not work and return : 
"/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/node_modules/leveldown/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: dlopen(/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/node_modules/leveldown/build/Release/leveldown.node, 1): no suitable image found.  Did find:
	/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/node_modules/leveldown/build/Release/leveldown.node: mach-o, but wrong architecture
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/node_modules/leveldown/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)"

GUI will never show and files will never synced. 

(I have try to install /uninstall multiple times and have to say that on the first time GUI was launching, even the icon tray)

EDIT : renaming /usr/local/lib/node_modules/cozy-desktop/node_modules/nodewebkit/package.json into _package.json allow me to launch UI, system icon tray is here and UI can be launched without errors. But sync is still not working

**Comment by Kloadut** [comment]
We are working on releasing a properly packaged version for GNU/Linux and OSX.
It should be released by next week.

**Comment by FromBabylon** [comment]
Still impossible to launch :

`node_modules/nodewebkit/bin/nodewebkit .
2015-03-26 11:25:19.065 node-webkit[13750:827670] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
[13750:0326/112519:ERROR:breakpad_mac.mm(234)] Breakpad initializaiton failed
2015-03-26 11:25:19.254 node-webkit Helper[13751:827709] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2015-03-26 11:25:19.395 node-webkit Helper[13752:827746] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
[13750:0326/112519:INFO:CONSOLE(343)] "Uncaught Error: Cannot find module './backend/config'", source: module.js (343)
[13750:0326/112519:INFO:CONSOLE(841)] "Uncaught TypeError: Property 'displayTrayMenu' of object [object Object] is not a function", source: file:///Users/Charlie/cozy-desktop/client/public/javascripts/app.js (841)`

**Comment by frankrousseau** [comment]
Can you try to use the prepackaged version available here?

https://github.com/cozy-labs/cozy-desktop/releases

It works in read-only mode. We want to validate this aspect before enabling writings from the device.

**Comment by FromBabylon** [comment]
Oups didn't see releases ! My bad
However download doesn't work

**Comment by frankrousseau** [comment]
No worry we didn't announce it clearly yet.

**Comment by FromBabylon** [comment]
Still same problem : blocked on initialization after half an hour. I am wondering if this has something to do with my cozy instance as problems are similar with cozy on android. 
Do I need to have sync installed in cozy instance ?

**Comment by frankrousseau** [comment]
If you have problems on your Android too, it looks like your Cozy is not working properly. The Sync module is not required.

Maybe it's related to self-signed certificate. We had a similar problem. Aside of that, Does your Cozy work well?

**Comment by FromBabylon** [comment]
Recurrent problems are : apps crashes or stack craches if I update more than one thing at a time. Every time a problem appears with updates, sync app doesn't work after and I need to reinstall it (However I can't reinstall it since yesterday problem)
However sync app (contacts and calendar sync) works very well when sync app is installed. 

Appart of that, I can't sync stuff either with cozy desktop or cozy mobile. (With cozy mobile some pictures are uploaded but it seems to be random). 

I use a self-signed cert

**Comment by frankrousseau** [comment]
There are many problems here. Can you remind me what is your distribution and the hardware on which you installed Cozy?

**Comment by FromBabylon** [comment]
What info do you need ?
Cozy is installed on a VPS running ubuntu 14.04

**Comment by frankrousseau** [comment]
How much RAM is available?

**Comment by FromBabylon** [comment]
3go

**Comment by frankrousseau** [comment]
Then can you run the following commands:

    sudo supervisortctl stop cozy-controller
    sudo kill -p node
    sudo supervisortctl start cozy-controller

Wait one minute then run the command:

    cozy-monitor status

**Comment by FromBabylon** [comment]
(`kill -p` doesn't work, used pkill)
Output : 
    :~$ cozy-monitor status
    info - Cannot get Cozy credentials. Are you sure you have the rights to access to:
    /etc/cozy/stack.token ?
    postfix: up
    couchdb: up
    controller: down
    data-system: down
    home: down
    proxy: down
    indexer: up

**Comment by frankrousseau** [comment]
Something is really weird, the controller doesn't start. Can you copy/past the controller logs:

/var/log/supervisorcozy-controller-stdout-****

**Comment by FromBabylon** [comment]
Sorry forgot to start it ! 
Output : 
    info - Cannot get Cozy credentials. Are you sure you have the rights to access to:
    /etc/cozy/stack.token ?
    postfix: up
    couchdb: up
    controller: up
    data-system: up
    home: up
    proxy: up
    indexer: up
    bookmarks: stopped
    calendar: stopped
    contacts: stopped
    photos: stopped
    piour-owm: stopped

**Comment by frankrousseau** [comment]
can you run these commands:

    cozy-monitor uninstall photos
    cozy-monitor install photos
    cozy-monitor install sync

and:

     cozy-monitor versions

**Comment by FromBabylon** [comment]
```
:~$ cozy-monitor install photos
info - Cannot get Cozy credentials. Are you sure you have the rights to access to:
/etc/cozy/stack.token ?
info - Install started for photos...
info - Cannot get Cozy credentials. Are you sure you have the rights to access to:
/etc/cozy/stack.token ?
error - An error occured:
Install home failed. Can't figure out the app state.

```
```
:~$ cozy-monitor install sync
info - Cannot get Cozy credentials. Are you sure you have the rights to access to:
/etc/cozy/stack.token ?
info - Install started for sync...
error - An error occured:
[Error: Expected application not listed in database after installation.]
Install home failed.
```
```
:~$ cozy-monitor versions
info - Cannot get Cozy credentials. Are you sure you have the rights to access to:
/etc/cozy/stack.token ?

Cozy Stack:
controller: 2.0.19
data-system: 1.0.27
home: 1.0.40
proxy: 1.0.13
indexer: 1.0.0
monitor: 1.2.10

Other applications:
bookmarks: 0.9.6
calendar: 1.0.12
contacts: 1.1.3
files: 1.1.4
photos: 1.0.9
piour-owm: 0.5.1
sync: 1.0.6
```

**Comment by FromBabylon** [comment]
After a fresh install of Cozy in a lxc container Cozy-desktop is now working. This means problem was linked to my Cozy install (on ubuntu 14.04). 
I think you can close issue. 

I can re-install it if you want to investigate further

**Comment by frankrousseau** [comment]
Ok, don't worry for now. Thank you for your time and patience!
