### ISSUE TITLE
sudo apt-get install nodejs-legacy build-essentials > KO

### ISSUE THREAD

**Issue by christi9n** [cozy-labs/cozy-desktop#85]
Hi,
Debian 7.8
When I do "sudo apt-get install nodejs-legacy build-essentatials"
I've got (for french speakers, sorry ;o)

"Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Aucune version du paquet nodejs-legacy n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source

E: Le paquet « nodejs-legacy » n'a pas de version susceptible d'être installée
E: Impossible de trouver le paquet build-essentatials"

**Comment by frankrousseau** [comment]
Je crois que cette ligne est valable pour Ubuntu. Pour vous il vaut mieux installer directement Node.js à partir des sources.

**Comment by combaudon** [comment]
Bonjour,
Effectivement, c'est OK maintenant.
Par contre bug:
Tout mes fichiers synchronisés font le même poid (20,8 Ko) et sont illisibles (.ODT, .PDF, .DOC) excepté les fichiers .JPG qui ont conservé aussi leur libellé mais à l'ouverture sont tous les mêmes!
En fait il s'agit d'un .JPG qui fait 20,8 Ko et que j'avais déposé dans un répertoire de "FILE" puis ensuite transféré via COZYCLOUD dans "PHOTO".
Cdlt

**Comment by frankrousseau** [comment]
Effectivement c'est la première fois qu'on nous le rapporte.

**Comment by nono** [comment]
La suite sur #86
