### ISSUE TITLE
Duplicated File after move 

### ISSUE THREAD

**Issue by aenario** [cozy-labs/cozy-desktop#850]
### Description

Race condition leads to duplicated file

### Steps to Reproduce

1. Create file
2. Move file to sub folder
3. Have bad luck

### Expected behavior

File only in subfolder

### Actual behavior

File appears in both root and subfolder

### Informations

* **reproductible**: sometimes
* **OS**: macOS
* **version**: build-developement-20172610

**Comment by aenario** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[#850] Duplication d'un fichier suite à un déplacement](https://trello.com/c/BcVfIp4s/429-850-duplication-dun-fichier-suite-%C3%A0-un-d%C3%A9placement)

**Comment by sebn** [comment]
Closing as the trello card has been archived.
