### ISSUE TITLE
Bug : tous les fichiers font 20.8Ko 

### ISSUE THREAD

**Issue by aenario** [cozy-labs/cozy-desktop#86]
This was originally reported by @combaudon at https://github.com/cozy/cozy-sync/issues/73

> Par contre bug:
>Tout mes fichiers synchronisés font le même poid (20,8 Ko) et sont illisibles (.ODT, .PDF, .DOC) excepté les fichiers .JPG qui ont conservé aussi leur libellé mais à l'ouverture sont tous les mêmes!
> En fait il s'agit d'un .JPG qui fait 20,8 Ko et que j'avais déposé dans un répertoire de "FILE" puis ensuite transféré via COZYCLOUD dans "PHOTO".

Salut @combaudon et désolé pour le retard. Nous avons mis le client desktop en standby pour le mois à venir pour se focaliser sur le client mail et j'ai laissé passer ton issue dans l'oubli. Toute mes excuses.

Pour ton problème, ça ressemble à une erreur de transfert mal géré par le client, qui mettrait du coup le message d'erreur dans les fichier à la place de leur contenu correct. Peux-tu essayer de changer l'extension d'un fichier en `.txt` et de l'ouvrir ?

**Comment by combaudon** [comment]
si je change l'extension en .txt le fichier est illisible !

**Comment by aenario** [comment]
Ok, donc ca doit bien être le contenu de l'image JPG qui est mit à la place de tous les fichiers. C'est particulièrement étrange...
Tu arrives bien à récupérer tes fichiers via l'interface web de cozy ?

Pour te débloquer, tu peux essayer une resynchro complête : arrêter cozy-desktop, puis 
```
rm -rf /ton/dossier/synchronisé
rm -rf ~/.cozy-desktop
cozy-desktop
```

**Comment by combaudon** [comment]
Bonjour et merci pour ton aide.

J'ai suivi ce que tu m'as demandé, j'ai reparamétré et maintenant mon dossier local reste désepérement vide, plus de synchronisation avec le serveur.
Pour info, je n'ai plus de répertoire ~/.cozy-desktop !?

**Comment by aenario** [comment]
Au temps pour moi, il faut reconfigurer le cozy :
```
cozy-desktop add-remote-cozy http://url.of.my.cozy devicename /sync/directory
```
Si tu souhaite utiliser le même nom de device, il faudra d'abord supprimer l'ancien device via l'interface web (onglet "gérer vos apps")

**Comment by combaudon** [comment]
C'est ce que j'avais refait et malgré cela pas plus de ~/.cozy-desktop

**Comment by aenario** [comment]
Ok, j'essaie de reproduire.
Tu installes avec le .deb ?

**Comment by combaudon** [comment]
Oui 

Le 10/04/2015 14:15, Romain Foucault a écrit : 

> Ok, j'essaie de reproduire.
> Tu installes avec le .deb ? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/cozy-labs/cozy-desktop/issues/86#issuecomment-91535030

**Comment by combaudon** [comment]
Bonsoir,
Debian 8 - 64bits
Ca y est, j'ai tout réinstallé, mais le comportement de synchronisation est incorrect:

Si je me place côté navigateur:
Répertoires
Je créé des répertoires (et sous-répertoires) > non visible en local (sauf si je stoppe puis relance "cosy-desktop sync")
Je modifie(renomme) des répertoires (et sous-répertoires) > non visible en local (sauf si je stoppe puis relance "cosy-desktop sync") et alors les répertoires sont doublés des deux côtés (les répertoires avec les noms originaux et ceux avec les nouveaux libellés)
Je supprime des répertoires (et sous-répertoires) > non visible en local même si je stoppe puis relance "cosy-desktop sync"
Fichiers (pdf, png, jpg, rtf, ...)
Je créé des fichiers > non visible en local (sauf si je stoppe puis relance "cosy-desktop sync")
Je renomme des fichiers > non visible en local (sauf si je stoppe puis relance "cosy-desktop sync") et alors les fichiers sont doublés des deux côtés (les fichiers avec les noms originaux et ceux avec les nouveaux libellés) > et le pb dont je parlais au début est toujours d'actualité
Je supprime des fichiers > non visible en local (sauf si je stoppe puis relance "cosy-desktop sync")

Si je me place en local
Répertoires
Je créé/modifie(renomme)/supprime des répertoires (et sous-répertoires) > visible dans le navigateur
Fichiers (pdf, png, jpg, rtf, ...)
Je créé/modifie(renomme)/supprime des fichiers > visible dans le navigateur

Et le fameux répertoire "Appareils photos" > je l'ai supprimé et recréé.
Pour rappel, mon LG G3 (android Lolipop) ne synchronise pas les photos dans ce répertoire

Bonsoir
Christian

**Comment by nono** [comment]
Hello, this bug has been resolved.
