### ISSUE TITLE
No automatic file syncing

### ISSUE THREAD

**Issue by phhorrein** [cozy-labs/cozy-desktop#88]
Hi all,

First of all, thanks for the great work on cozy. I’ve been experimenting with it in the last weeks and it is a real pleasure to use. 

I’ve got an issue with the Cozy Desktop syncing application. When I start the daemon, it correctly recovers files from the Cozy server. However, when I add or modify a file on the server while the application is running, it is not taken into account, and I need to restart it. By the way, I also have strange behavior on locally created and deleted files, but I guess this must be linked to the read only version.

I’m using the .deb file to install cozy-desktop, on a Debian jessie (testing). I tried to build it myself with npm, but it fails because of external dependencies. However, it cannot install fsevents due to incompatible architecture (requires darwin), I don’t know if it is linked. I run my cozy server in a docker container, with only 443 and 80 ports forwarded.

Is it a normal behavior in the current version ?

Pierre-Henri

**Comment by frankrousseau** [comment]
@phhorrein Thank you for your bug repot and your feedback. What you experience is a bug. But, I'm sad to say that currently we decided to stop working on the desktop client to focus on the Cozy webmail. I can't give you a date about when we'll be back on fixing and improving the desktop client.

Sorry for the inconvenience but we had to focus to make significant progress.

**Comment by phhorrein** [comment]
OK, too bad. Thanks for your reply anyway, and I hope you will have time to focus on the desktop client soon!

**Comment by nono** [comment]
Hello,
I'm the new developer in charge of cozy-desktop and my works in the last months has been released as a new version of cozy-desktop. It should resolve your issues (feel free to open more issues for bugs and suggestions).
