### ISSUE TITLE
Changing focus shouldn't hide the application window when using tiling window managers

### ISSUE THREAD

**Issue by moritzheiber** [cozy-labs/cozy-desktop#892]
### Description

When I open the Cozy window from the tray it opens regularly. However, once I focus another window (e.g. a file manager) the window disappears again. I would expect it to stay open so I can interact with it.

### Steps to Reproduce

1. Start Cozy Drive
2. Start another application
3. Watch the Cozy Drive window disappear

### Expected behavior

I would expect the window to stay open so I can interact with it.

### Actual behavior

It disappears.

### Informations

* **reproductible**:  always
* **OS**: Linux, Ubuntu 17.04, i3 window manager
* **version**: 3.4.0-beta1

**Comment by sebn** [comment]
Thank you very much for your feedback !

The UI is actually supposed to behave like a popover, same as Dropbox.
But your expectation definitely makes sense when using a tiling window manager.

Would you mind me renaming the issue to include the tiling aspect in the title and tagging it as a feature request?

Also please note the Linux AppImage is still beta, we're actually encountering auto-update issues, so you may have to downoad and install the next release by hand (we're really sorry for this).

**Comment by moritzheiber** [comment]
My apologies for the late reply. Apparently the mailserver I recently moved had an alias missing which was swallowing up all the email to the address which is registered with GitHub.

I've changed the title accordingly. I think I'm unable to add tags to the issue though.

Concerning the behavior in general: I don't know about the modal that Dropbox applies (I've never used their client), but I wouldn't consider the UX you describe really useful .. ? Maybe I'm missing the point though.

**Comment by moritzheiber** [comment]
(And don't worry about the AppImage issues, that's fair; I'm also running alpha builds of the newer Cozy stack, I'm all bleeding edge as it is)

**Comment by moritzheiber** [comment]
@sebn Sorry for the delay, for some reason GitHub stopped delivering email notifications. I only learned of this since yesterday and had them lift the "temporary" restrictions imposed on my account.

I find the window to be very relevant, it just doesn't behave like a window I would take a lot of information from. Also, it's the only application (!) that behaves that way, hence my slight irritation I guess.

My suggestion would be to just have it be its own independent window, like any other, and have users interact with it like any other window. Does that make sense?

**Comment by sebn** [comment]
>  Does that make sense?

Definitely. The app should display as a normal window instead of a popover when a tiling window manager is detected. But we're quite busy right now, so I can't promise anything yet.

**Comment by moritzheiber** [comment]
That's understandable. I mean, the current modal isn't broken, it's just inconvenient. So you can get to it once you have the time :slightly_smiling_face:

**Comment by sebn** [comment]
This should be fixed in the upcoming 3.6.0 release. Better wait for a stable version (the current beta is still under heavy testing).
