### ISSUE TITLE
Missing interface on GNU/Linux

### ISSUE THREAD

**Issue by y-lohse** [cozy-labs/cozy-desktop#984]
On GNU/Linux, Cozy-drive interface doesn't show up when the tray icon is clicked. The only thing that appears with a left or right click is a popup menu with only one entry ("Quit").

Tested with Kubuntu 17.10
```
$ plasmashell --version
plasmashell 5.10.5
$ kf5-config --version
Qt : 5.9.1
Framework KDE : 5.38.0
kf5-config : 1.0
```

_______

Originally reported [here](https://github.com/cozy/cozy-drive/issues/772) cc @hieroy

**Comment by sebn** [comment]
Thanks for reporting, @y-lohse & @hleroy!

We didn't extensively test the app on KDE yet. We had to fix a similar issue on Unity, so making it work on KDE should be easy, although we're quite busy right now.

Pointer for anybody willing to fix it (including ourselves):

1. Clone the repo
2. `grep -ri unity gui/js/`.
3. Fix the code (the fix should be relatively easy, even if you don't know JavaScript very well)
4. Make sure it works on your KDE desktop
5. Open the PR and make sure CI is green (in case it is not, we'll help you fix it)

**Comment by hleroy** [comment]
Thanks @y-lohse for transferring the issue to the correct repo.
@sebn I'll have a look at the source code, thanks for pointing out where to start looking

**Comment by sebn** [comment]
👌

**Comment by sebn** [comment]
Lost the fix note in commit while squashing... Fixed in https://github.com/cozy-labs/cozy-desktop/commit/d1d76ae0609e12949d38d80c3ac072d603de6a3d
