### ISSUE TITLE
Support Desktop integration when running AppImage on GNU/Linux

### ISSUE THREAD

**Issue by y-lohse** [cozy-labs/cozy-desktop#985]
Cozy-drive AppImage should provide an optional desktop integration, i.e. creating Desktop Entry file (with .desktop extension) inside of ~/.config/autostart
When auto-updating, Cozy-drive should take care of updating the Desktop Entry with the new AppImage path.

_________

Originally reported [here](https://github.com/cozy/cozy-drive/issues/773) cc @hieroy

**Comment by sebn** [comment]
Well the AppImage is supposed to create the desktop entry at first launch.
And the auto-update is supposed to update the desktop entry too.

@hleroy Which version of the app are you using?

**Comment by hleroy** [comment]
First version installed was CozyDrive-3.4.2-x86_64
It was auto-updated to 3.4.3

I also had sync issues which I reported on the [forum](https://forum.cozy.io/t/deplacement-inattendu-de-fichiers-vers-la-corbeille/5430/6). I will clear up all configuration on my devices and give it a fresh start.

**Comment by hleroy** [comment]
The documentation page for the GNU/Linux client (https://docs.cozy.io/fr/sync/linux/) should link to [Cozy Drive on the GNU/Linux Desktop](https://github.com/cozy-labs/cozy-desktop/blob/master/doc/usage/linux.md), which provide more details.

**Comment by hleroy** [comment]
Since I'm not familiar with AppImage, I may have run it once from the download folder, then later moved it to `/opt/cozy` and I ran it again.

I removed the program entirely (including `~/.cozy-desktop`), then I did the first run directly from `/opt/cozy`

The `*.desktop` files have been created in:
`~/.local/share/applications/`
`~/.config/autostart`

This issue can be closed. Many thanks.

**Comment by probonopd** [comment]
Are you running the optional `appimaged` daemon? It can do desktop integration (menus, icons) automatically.

**Comment by hleroy** [comment]
No, I'm not using `appimaged`. Actually the integration works well (application list and startup folder) as long as the AppImage is not moved on the file system after the first launch.

**Comment by sebn** [comment]
@probonopd We were aware of the `appimaged` daemon, but didn't mention it in the installation documentation. I'll fix it. Thanks for pointing this out!

**Comment by sebn** [comment]
@hleroy 

> The documentation page for the GNU/Linux client (https://docs.cozy.io/fr/sync/linux/) should link to Cozy Drive on the GNU/Linux Desktop, which provide more details.

This will be fixed, thanks for pointing this out too!

I'll close this issue as soon as the doc is up-to-date.

**Comment by sebn** [comment]
Link [added](https://docs.cozy.io/en/sync/linux/#more). Closing.
