### ISSUE TITLE
Systray icon on GNU/Linux with KDE

### ISSUE THREAD

**Issue by hleroy** [cozy-labs/cozy-desktop#990]
### Description

Systray icon is different on KDE than with Windows / MacOS. It's not the usual cozy cloud but rather some sort of folder.
See screenshots in both light and dark theme under KDE:
![screenshot_20180219_214836](https://user-images.githubusercontent.com/1446015/36396648-7db28022-15bf-11e8-8e18-5b7f00377f6e.png)
![screenshot_20180219_214930](https://user-images.githubusercontent.com/1446015/36396652-80445be4-15bf-11e8-848a-e260f3cf02f6.png)

### Steps to Reproduce

Launch AppImage on Kubuntu 17.10 desktop.

### Expected behavior

Cloud-like systray icon as found in gui/images/tray-icon-linux/

### Actual behavior

Some sort of folder icon appears.

### Informations

I have searched the repo for all image assets, and I can't find even find where the folder icon comes from :-/
The code in gui/js/tray.js is supposed to use gui/images/tray-icon-linux/

**Comment by sebn** [comment]
Hello @hleroy, thanks for reporting!

This is actually the same icon, zoomed in and cropped.
I'm almost sure we already saw this issue in another desktop environment.
We didn't take the time to investigate yet.

**Comment by hleroy** [comment]
If it's a scaling issue, I will have a look at the Electron framework documentation. It may be related to the icon size, DPI or something like that. I hope to come up with a new PR soon.

**Comment by hleroy** [comment]
@sebn : many other Electron projects have the same issue with tray icon scaling on KDE. Until this is fixed in Electron (and/or KDE), I have patched the code to use a 22*22 icon size when KDE environment is detected. I have tested the AppImage successfully with Kubuntu 17.10 and Mageia 6.

**Comment by hleroy** [comment]
Fixed in [3.5.0](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.5.0)

**Comment by ArchangeGabriel** [comment]
The fix landed in Chromium (see comments starting from https://github.com/vector-im/riot-web/issues/6767#issuecomment-412674274, they are other interesting information regarding tray icons btw).

**Comment by ArchangeGabriel** [comment]
Electron 5.x now has the fixed Chromium, so that scaling down the icon won’t be necessary anymore when the used Electron will be upgraded. Note that with current version, you can also workaround that by setting `XDG_CURRENT_DESKTOP=Unity`.
